{{- if .Values.openmatch.security.networkpolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: open-match-pod
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  podSelector:
    matchLabels:
      open-match-pod: "true"
  policyTypes:
  - Egress
  egress:
  - {} # No restrictions
{{- end }}
