apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-mmforc
  labels:
    app: openmatch
    component: mmforc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmatch
      component: mmforc
  template:
    metadata:
      labels:
        app: openmatch
        component: mmforc
    spec:
      containers:
      - name: om-mmforc
        image: gcr.io/open-match-public-images/openmatch-mmforc
        #imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
