// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/mmlogic.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryTicketsRequest struct {
	// The Pool representing the set of Filters to be queried.
	Pool *Pool `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// Tenant ID is the ID used to differentiate tenants in the same Open Match cluster.
	TenantId             string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTicketsRequest) Reset()         { *m = QueryTicketsRequest{} }
func (m *QueryTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTicketsRequest) ProtoMessage()    {}
func (*QueryTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa9c8aeaf311764, []int{0}
}

func (m *QueryTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketsRequest.Unmarshal(m, b)
}
func (m *QueryTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketsRequest.Marshal(b, m, deterministic)
}
func (m *QueryTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketsRequest.Merge(m, src)
}
func (m *QueryTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTicketsRequest.Size(m)
}
func (m *QueryTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketsRequest proto.InternalMessageInfo

func (m *QueryTicketsRequest) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

func (m *QueryTicketsRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type QueryTicketsResponse struct {
	// The Tickets that meet the Filter criteria requested by the Pool.
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryTicketsResponse) Reset()         { *m = QueryTicketsResponse{} }
func (m *QueryTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTicketsResponse) ProtoMessage()    {}
func (*QueryTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa9c8aeaf311764, []int{1}
}

func (m *QueryTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketsResponse.Unmarshal(m, b)
}
func (m *QueryTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketsResponse.Marshal(b, m, deterministic)
}
func (m *QueryTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketsResponse.Merge(m, src)
}
func (m *QueryTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTicketsResponse.Size(m)
}
func (m *QueryTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketsResponse proto.InternalMessageInfo

func (m *QueryTicketsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTicketsRequest)(nil), "api.QueryTicketsRequest")
	proto.RegisterType((*QueryTicketsResponse)(nil), "api.QueryTicketsResponse")
}

func init() { proto.RegisterFile("api/mmlogic.proto", fileDescriptor_caa9c8aeaf311764) }

var fileDescriptor_caa9c8aeaf311764 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0xaa, 0xfd, 0x3a, 0xfd, 0x16, 0x30, 0xfc, 0x28, 0x0d, 0x3f, 0x1a, 0x02, 0x48,
	0x21, 0x22, 0x9e, 0xd4, 0x74, 0x15, 0x54, 0xa9, 0x85, 0x76, 0x11, 0x29, 0x01, 0x6a, 0x10, 0x0b,
	0x36, 0x68, 0x32, 0xbe, 0xd8, 0x43, 0xec, 0xb9, 0x53, 0xcf, 0x38, 0xa5, 0x5b, 0x1e, 0x01, 0x76,
	0xbc, 0x0c, 0x0f, 0xc1, 0x2b, 0x20, 0x1e, 0x80, 0x27, 0x40, 0xb6, 0x89, 0x5a, 0xd4, 0xac, 0x46,
	0x73, 0xce, 0xb9, 0xe7, 0x5e, 0x9d, 0x7b, 0xc9, 0x55, 0x61, 0x14, 0xcf, 0xf3, 0x0c, 0x13, 0x25,
	0x03, 0x53, 0xa0, 0x43, 0xda, 0x12, 0x46, 0x75, 0x68, 0x8d, 0x83, 0xb5, 0x22, 0x01, 0xdb, 0x10,
	0x9d, 0xdb, 0x09, 0x62, 0x92, 0x01, 0xaf, 0x28, 0xa1, 0x35, 0x3a, 0xe1, 0x14, 0xea, 0x25, 0xfb,
	0xb8, 0x7e, 0xe4, 0x20, 0x01, 0x3d, 0xb0, 0xa7, 0x22, 0x49, 0xa0, 0xe0, 0x68, 0x6a, 0xc5, 0x65,
	0x75, 0xf7, 0x98, 0x5c, 0x3b, 0x2e, 0xa1, 0x38, 0x7b, 0xa3, 0xe4, 0x1c, 0x9c, 0x8d, 0xe0, 0xa4,
	0x04, 0xeb, 0xe8, 0x1d, 0xb2, 0x66, 0x10, 0xb3, 0xb6, 0xc7, 0xbc, 0xde, 0x56, 0xb8, 0x19, 0x08,
	0xa3, 0x82, 0x57, 0x88, 0x59, 0x54, 0xc3, 0xf4, 0x16, 0xd9, 0x74, 0xa0, 0x85, 0x76, 0xef, 0x55,
	0xdc, 0xf6, 0x99, 0xd7, 0xdb, 0x8c, 0xfe, 0x6b, 0x80, 0x71, 0xdc, 0xdd, 0x23, 0xd7, 0xff, 0xb5,
	0xb4, 0x06, 0xb5, 0x05, 0xfa, 0x90, 0x6c, 0xb8, 0x06, 0x6a, 0x7b, 0xac, 0xd5, 0xdb, 0x0a, 0xb7,
	0x6a, 0xdb, 0x46, 0x16, 0x2d, 0xb9, 0x70, 0x41, 0x36, 0xa6, 0xf9, 0xa4, 0xca, 0x81, 0xce, 0xc9,
	0xff, 0x17, 0x9d, 0x68, 0xbb, 0x2e, 0x58, 0x31, 0x6f, 0x67, 0x7b, 0x05, 0xd3, 0xb4, 0xed, 0x3e,
	0xf8, 0xfc, 0xe3, 0xe7, 0x57, 0xff, 0x6e, 0x77, 0x9b, 0x2f, 0x76, 0x96, 0x09, 0xf3, 0xbf, 0xcd,
	0x46, 0x27, 0x55, 0xc5, 0xc8, 0xeb, 0x0f, 0xbd, 0x67, 0xbf, 0xfd, 0x2f, 0x07, 0xbf, 0x7c, 0xfa,
	0xdd, 0x23, 0x37, 0xa6, 0x53, 0x56, 0x0f, 0xc0, 0x7a, 0x87, 0xc2, 0x09, 0x36, 0x11, 0x67, 0x50,
	0x3c, 0xea, 0x8e, 0x09, 0x79, 0x69, 0x40, 0xb3, 0xa9, 0x70, 0x32, 0xa5, 0x37, 0x53, 0xe7, 0x8c,
	0x1d, 0x71, 0x8e, 0x06, 0xf4, 0x20, 0xaf, 0xb0, 0x20, 0x86, 0x45, 0xe7, 0xfe, 0xf9, 0x7f, 0x10,
	0x2b, 0x2b, 0x4b, 0x6b, 0xf7, 0x9b, 0x7d, 0x25, 0x05, 0x96, 0xc6, 0x06, 0x12, 0xf3, 0xfe, 0x5b,
	0x42, 0x0f, 0x8c, 0x90, 0x29, 0xb0, 0x30, 0x18, 0xb2, 0x89, 0x92, 0x50, 0x05, 0xb4, 0xbf, 0xb4,
	0x4c, 0x94, 0x4b, 0xcb, 0x59, 0xa5, 0xe4, 0x4d, 0xe9, 0x07, 0x2c, 0x12, 0x91, 0x83, 0xbd, 0xd0,
	0x8c, 0xcf, 0x32, 0x9c, 0xf1, 0x5c, 0x58, 0x07, 0x05, 0x9f, 0x8c, 0x9f, 0x1f, 0xbd, 0x78, 0x7d,
	0x14, 0xb6, 0x76, 0x82, 0x61, 0xdf, 0xf7, 0xfc, 0xf0, 0x8a, 0x30, 0x26, 0x53, 0xb2, 0x5e, 0x35,
	0xff, 0x68, 0x51, 0x8f, 0x2e, 0x21, 0xd1, 0x53, 0xd2, 0xda, 0x1d, 0xee, 0xd2, 0x5d, 0xd2, 0x8f,
	0xc0, 0x95, 0x85, 0x86, 0x98, 0x9d, 0xa6, 0xa0, 0x99, 0x4b, 0x81, 0x15, 0x60, 0xb1, 0x2c, 0x24,
	0xb0, 0x18, 0xc1, 0x32, 0x8d, 0x8e, 0xc1, 0x27, 0x65, 0x5d, 0x40, 0xd7, 0xc9, 0xda, 0x37, 0xdf,
	0xdb, 0x28, 0xf6, 0x48, 0xfb, 0x3c, 0x0c, 0x76, 0x88, 0xb2, 0xcc, 0x41, 0x37, 0xa7, 0x45, 0xef,
	0xad, 0x8e, 0x86, 0x5b, 0xe5, 0x80, 0xc7, 0x28, 0x2d, 0x7f, 0xb7, 0x6e, 0xe6, 0x09, 0x37, 0xb3,
	0xd9, 0x7a, 0x7d, 0x85, 0x4f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x4d, 0x9d, 0x8f, 0xff,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MmLogicClient is the client API for MmLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MmLogicClient interface {
	// QueryTickets gets the list of Tickets that match every Filter in the
	// specified Pool.
	QueryTickets(ctx context.Context, in *QueryTicketsRequest, opts ...grpc.CallOption) (MmLogic_QueryTicketsClient, error)
}

type mmLogicClient struct {
	cc *grpc.ClientConn
}

func NewMmLogicClient(cc *grpc.ClientConn) MmLogicClient {
	return &mmLogicClient{cc}
}

func (c *mmLogicClient) QueryTickets(ctx context.Context, in *QueryTicketsRequest, opts ...grpc.CallOption) (MmLogic_QueryTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MmLogic_serviceDesc.Streams[0], "/api.MmLogic/QueryTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &mmLogicQueryTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MmLogic_QueryTicketsClient interface {
	Recv() (*QueryTicketsResponse, error)
	grpc.ClientStream
}

type mmLogicQueryTicketsClient struct {
	grpc.ClientStream
}

func (x *mmLogicQueryTicketsClient) Recv() (*QueryTicketsResponse, error) {
	m := new(QueryTicketsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MmLogicServer is the server API for MmLogic service.
type MmLogicServer interface {
	// QueryTickets gets the list of Tickets that match every Filter in the
	// specified Pool.
	QueryTickets(*QueryTicketsRequest, MmLogic_QueryTicketsServer) error
}

func RegisterMmLogicServer(s *grpc.Server, srv MmLogicServer) {
	s.RegisterService(&_MmLogic_serviceDesc, srv)
}

func _MmLogic_QueryTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTicketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MmLogicServer).QueryTickets(m, &mmLogicQueryTicketsServer{stream})
}

type MmLogic_QueryTicketsServer interface {
	Send(*QueryTicketsResponse) error
	grpc.ServerStream
}

type mmLogicQueryTicketsServer struct {
	grpc.ServerStream
}

func (x *mmLogicQueryTicketsServer) Send(m *QueryTicketsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MmLogic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MmLogic",
	HandlerType: (*MmLogicServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryTickets",
			Handler:       _MmLogic_QueryTickets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/mmlogic.proto",
}
